laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('encontros-e-mais', 'AgendaController@index')->name('agenda');
    Route::get('joalheiros', 'JoalheirosController@index')->name('joalheiros');
    Route::get('joalheiros/{slug}', 'JoalheirosController@show')->name('joalheiros.show');
    Route::get('escolas-e-grupos', 'EscolasGruposController@index')->name('escolas-e-grupos');
    Route::get('escolas-e-grupos/{slug}', 'EscolasGruposController@show')->name('escolas-e-grupos.show');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::get('filtro', 'FiltroController@filtrar')->name('filtro');
    Route::get('filtro/{pais}', 'FiltroController@getJoalheirosPais')->name('filtro.pais');

    // USUARIO LOGADO
    Route::get('ebook/download/{user}', 'HomeController@download')->name('ebook.download');
    Route::get('assine-livro/{user}', 'AssineLivroController@index')->name('assine-livro');
    Route::post('assine-livro/{user}', 'AssineLivroController@post')->name('assine-livro.post');
    Route::get('area-restrita/{user}', 'CadastrosFavoritasController@index')->name('favoritas');
    Route::post('favoritas/{user}/{joia}', 'CadastrosFavoritasController@favoritar')->name('favoritas.post');
    Route::delete('favoritas/{user}/{joia}', 'CadastrosFavoritasController@desfavoritar')->name('favoritas.delete');
    Route::get('palestra/zoom/{user}/{palestra}', 'AgendaController@relatorio')->name('relatorio.zoom');
    Route::get('compartilhar/whatsapp/{user}/{joia}', 'CadastrosFavoritasController@relatorioWhatsapp')->name('relatorio.whatsapp.compartilhar');
    Route::get('compartilhar/facebook/{user}/{joia}', 'CadastrosFavoritasController@relatorioFacebook')->name('relatorio.facebook.compartilhar');
    Route::get('compartilhar/email/{user}/{joia}', 'CadastrosFavoritasController@relatorioEmail')->name('relatorio.email.compartilhar');

    // Idiomas
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if (in_array($idioma, ['pt', 'en', 'es'])) {
            Session::put('locale', $idioma);
        }
        return redirect()->back();
    })->name('lang');

    // Login Evento
    Route::group([
        'prefix' => 'evento',
        'namespace' => 'Evento',
    ], function () {
        Route::post('login', 'Auth\AuthController@login')->name('evento.login.post');
        Route::post('cadastro', 'Auth\AuthController@create')->name('evento.register.post');
        Route::post('atualizar/{user}', 'Auth\AuthController@update')->name('evento.atualizar.user');
        Route::post('esqueci-minha-senha', 'Auth\PasswordController@sendResetLinkEmail')->name('evento.password-request.post');
        Route::get('redefinicao-de-senha/{token}', 'Auth\PasswordController@showResetForm')->name('evento.password-reset');
        Route::post('redefinicao-de-senha', 'Auth\PasswordController@reset')->name('evento.password-reset.post');
        Route::get('logout', 'Auth\AuthController@logout')->name('evento.logout');
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::resource('grupos-escolas', 'GruposEscolasController');
        Route::resource('joalheiros', 'JoalheirosController');
        Route::resource('joalheiros.joias', 'JoalheirosJoiasController');
        Route::resource('joalheiros.processo', 'JoalheirosProcessoController');
        Route::resource('joalheiros.serie', 'JoalheirosSerieController');
        Route::resource('banners-evento', 'BannersEventoController');
        Route::resource('banners-joalheiros', 'BannersJoalheirosController');
        Route::resource('banners-revista', 'BannersRevistaController');
        Route::resource('evento', 'EventoController', ['only' => ['index', 'update']]);
        Route::resource('tipos', 'TiposController');
        Route::resource('agenda', 'AgendaController', ['except' => 'show']);
        Route::resource('agenda.palestras', 'AgendaPalestrasController');
        Route::resource('videos', 'VideosController');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        Route::get('cadastros', 'CadastrosController@index')->name('painel.cadastros.index');
        Route::resource('assinaturas-livro', 'AssinaturasLivroController', ['only' => ['index', 'destroy']]);
        Route::get('relatorios/download-ebook', 'RelatoriosController@downloadEbook')->name('painel.relatorios.download-ebook');
        Route::get('relatorios/palestra-zoom', 'RelatoriosController@palestraZoom')->name('painel.relatorios.palestra-zoom');
        Route::get('relatorios/compartilhar-joia', 'RelatoriosController@compartilharJoia')->name('painel.relatorios.compartilhar-joia');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Joalheiro.php
<?php

namespace App\Models;

use App\Helpers\CropImage;
use Illuminate\Database\Eloquent\Model;

use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

class Joalheiro extends Model implements SluggableInterface
{
    use SluggableTrait;

    protected $sluggable = [
        'build_from' => 'nome',
        'save_to'    => 'slug',
        'on_update'  => true
    ];

    protected $table = 'joalheiros';

    protected $guarded = ['id'];

    public function joias()
    {
        return $this->hasMany('App\Models\JoalheiroJoia', 'joalheiro_id')->ordenados();
    }

    public static function upload_capa()
    {
        return CropImage::make('capa', [
            [
                'width'  => 600,
                'height' => null,
                'path'   => 'assets/img/joalheiros/'
            ],
            [
                'width'  => 280,
                'height' => 280,
                'path'   => 'assets/img/joalheiros/thumbs/'
            ]
        ]);
    }

    public static function upload_capa_ateliers()
    {
        return CropImage::make('capa_ateliers', [
            'width'  => 280,
            'height' => 280,
            'path'   => 'assets/img/joalheiros/ateliers/'
        ]);
    }
}

laravel/app/Http/Controllers/JoalheirosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Models\Joalheiro;
use App\Models\JoalheiroJoia;
use App\Models\JoalheiroProcesso;
use App\Models\JoalheiroSerie;

class JoalheirosController extends Controller
{
    public function index()
    {
        $joalheiros = Joalheiro::join('paises', 'paises.id', '=', 'joalheiros.pais_id')
            ->select('paises.nome as pais_nome', 'paises.nome_en as pais_nome_en', 'paises.nome_es as pais_nome_es', 'joalheiros.*')
            ->orderBy('nome', 'asc')->get();

        return view('frontend.joalheiros', compact('joalheiros'));
    }

    public function show($slug)
    {
        $joalheiro = Joalheiro::join('paises', 'paises.id', '=', 'joalheiros.pais_id')
            ->select('paises.nome as pais_nome', 'paises.nome_en as pais_nome_en', 'paises.nome_es as pais_nome_es', 'joalheiros.*')
            ->where('slug', $slug)->first();

        $joias = JoalheiroJoia::join('tipos', 'tipos.id', '=', 'joalheiros_joias.tipo_id')
            ->select('tipos.titulo as tipo', 'tipos.titulo_en as tipo_en', 'tipos.titulo_es as tipo_es', 'joalheiros_joias.*')
            ->where('joalheiros_joias.joalheiro_id', $joalheiro->id)
            ->ordenados()->get();

        $processo = JoalheiroProcesso::where('joalheiro_id', $joalheiro->id)->first();

        $serie = JoalheiroSerie::where('joalheiro_id', $joalheiro->id)->first();

        $joalheiros = Joalheiro::join('paises', 'paises.id', '=', 'joalheiros.pais_id')
            ->select('paises.nome as pais_nome', 'paises.nome_en as pais_nome_en', 'paises.nome_es as pais_nome_es', 'joalheiros.*')
            ->inRandomOrder()->take(4)->get();

        // $access_token = "My_Access_Token";
        // $photo_count = 5;
        // $json_link = "https://api.instagram.com/v1/users/self/media/recent/?";
        // $json_link .= "access_token={$access_token}&count={$photo_count}";
        // $json = file_get_contents($json_link);
        // $obj = json_decode(preg_replace('/("\w+"):(\d+)/', '\\1:"\\2"', $json), true);

        // dd($obj);

        return view('frontend.joalheiros-show', compact('joalheiro', 'joias', 'processo', 'serie', 'joalheiros'));
    }
}

laravel/app/Http/Controllers/Painel/JoalheirosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\JoalheirosRequest;
use App\Models\Joalheiro;
use App\Models\Pais;

class JoalheirosController extends Controller
{
    public function index()
    {
        $registros = Joalheiro::join('paises', 'paises.id', '=', 'joalheiros.pais_id')
            ->select('paises.nome as pais_nome', 'joalheiros.*')
            ->orderBy('nome', 'ASC')->get();

        return view('painel.joalheiros.index', compact('registros'));
    }

    public function create()
    {
        $paises = Pais::orderBy('nome', 'asc')->pluck('nome', 'id');

        return view('painel.joalheiros.create', compact('paises'));
    }

    public function store(JoalheirosRequest $request)
    {
        try {
            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Joalheiro::upload_capa();
            if (isset($input['capa_ateliers'])) $input['capa_ateliers'] = Joalheiro::upload_capa_ateliers();

            Joalheiro::create($input);

            return redirect()->route('painel.joalheiros.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Joalheiro $registro)
    {
        $paises = Pais::orderBy('nome', 'asc')->pluck('nome', 'id');

        return view('painel.joalheiros.edit', compact('registro', 'paises'));
    }

    public function update(JoalheirosRequest $request, Joalheiro $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Joalheiro::upload_capa();
            if (isset($input['capa_ateliers'])) $input['capa_ateliers'] = Joalheiro::upload_capa_ateliers();

            $registro->update($input);

            return redirect()->route('painel.joalheiros.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Joalheiro $registro)
    {
        try {
            $registro->delete();

            return redirect()->route('painel.joalheiros.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/joalheiros/processo/create.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>{{ $joalheiro->nome }} /</small> Adicionar Processo</h2>
</legend>

{!! Form::model($joalheiro, [
'route' => ['painel.joalheiros.processo.store', $joalheiro->id],
'method' => 'post',
'files' => true])
!!}

@include('painel.joalheiros.processo.form', ['submitText' => 'Inserir'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/joalheiros/processo/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>{{ $joalheiro->nome }} /</small> Editar Processo</h2>
    </legend>

    {!! Form::model($processo, [
        'route'  => ['painel.joalheiros.processo.update', $joalheiro->id, $processo->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.joalheiros.processo.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/joalheiros/processo/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('video', 'Vídeo (Opcional)') !!}
    {!! Form::text('video', null, ['class' => 'form-control']) !!}
    <p class="alerta-quantidade">Incluir aqui somente a parte da url após o "v=". Exemplo: https://www.youtube.com/watch?v=<strong>Y4goaZhNt4k</strong></p>
</div>

<div class="well form-group">
    {!! Form::label('imagem1', 'Imagem 1 (Opcional)') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/joalheiros/processo/thumbs/'.$processo->imagem1) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
    @endif
    {!! Form::file('imagem1', ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem2', 'Imagem 2 (Opcional)') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/joalheiros/processo/thumbs/'.$processo->imagem2) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
    @endif
    {!! Form::file('imagem2', ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem3', 'Imagem 3 (Opcional)') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/joalheiros/processo/thumbs/'.$processo->imagem3) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
    @endif
    {!! Form::file('imagem3', ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem4', 'Imagem 4 (Opcional)') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/joalheiros/processo/thumbs/'.$processo->imagem4) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
    @endif
    {!! Form::file('imagem4', ['class' => 'form-control']) !!}
</div>

<hr>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

laravel/resources/views/painel/joalheiros/processo/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<a href="{{ route('painel.joalheiros.index') }}" title="Voltar para Expositores" class="btn btn-sm btn-default">
    &larr; Voltar para Joalheiros </a>

<legend>
    <h2>
        {{ $joalheiro->nome }} | Processo
        @if(empty($processo))
        <a href="{{ route('painel.joalheiros.processo.create', $joalheiro->id) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar</a>
        @endif
    </h2>
    <p class="alerta-quantidade">Podem ser adicionadas até 4 imagens e 1 vídeo</p>
</legend>

@if(empty($processo))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>

@else
<div class="processo">
    <h4 class="titulo">Vídeo (YouTube):</h4>
    @if ($processo->video)
    <iframe src="https://www.youtube.com/embed/{{ $processo->video }}" width="760" height="430" frameborder="0" allow="autoplay; fullscreen" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    @else
    <p class="paragrafo">Sem vídeo</p>
    @endif

    <hr>

    <h4 class="titulo">Imagens:</h4>
    @if ($processo->imagem1)
    <img src="{{ asset('assets/img/joalheiros/processo/thumbs/'.$processo->imagem1) }}" alt="" class="processo-img">
    <hr>
    @endif

    @if ($processo->imagem2)
    <img src="{{ asset('assets/img/joalheiros/processo/thumbs/'.$processo->imagem2) }}" alt="" class="processo-img">
    <hr>
    @endif

    @if ($processo->imagem3)
    <img src="{{ asset('assets/img/joalheiros/processo/thumbs/'.$processo->imagem3) }}" alt="" class="processo-img">
    <hr>
    @endif

    @if ($processo->imagem4)
    <img src="{{ asset('assets/img/joalheiros/processo/thumbs/'.$processo->imagem4) }}" alt="" class="processo-img">
    <hr>
    @endif

    @if(!$processo->imagem1 && !$processo->imagem2 && !$processo->imagem3 && !$processo->imagem4)
    <p class="paragrafo">Sem imagens</p>
    <hr>
    @endif
</div>

{!! Form::open([
'route' => ['painel.joalheiros.processo.destroy', $joalheiro->id, $processo->id],
'method' => 'delete'
]) !!}

<button type="submit" class="btn btn-danger btn-sm btn-delete" style="margin-right:10px;"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>

<a href="{{ route('painel.joalheiros.processo.edit', [$joalheiro->id, $processo->id] ) }}" class="btn btn-primary btn-sm pull-left" style="margin-right:10px;">
    <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
</a>

@endif

@endsection