laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('encontros-e-mais', 'AgendaController@index')->name('agenda');
    Route::get('joalheiros', 'JoalheirosController@index')->name('joalheiros');
    Route::get('joalheiros/{slug}', 'JoalheirosController@show')->name('joalheiros.show');
    Route::get('escolas-e-grupos', 'EscolasGruposController@index')->name('escolas-e-grupos');
    Route::get('escolas-e-grupos/{slug}', 'EscolasGruposController@show')->name('escolas-e-grupos.show');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::get('filtro', 'FiltroController@filtrar')->name('filtro');
    Route::get('filtro/{pais}', 'FiltroController@getJoalheirosPais')->name('filtro.pais');

    // USUARIO LOGADO
    Route::get('ebook/download/{user}', 'HomeController@download')->name('ebook.download');
    Route::get('assine-livro/{user}', 'AssineLivroController@index')->name('assine-livro');
    Route::post('assine-livro/{user}', 'AssineLivroController@post')->name('assine-livro.post');
    Route::get('area-restrita/{user}', 'CadastrosFavoritasController@index')->name('favoritas');
    Route::post('favoritas/{user}/{joia}', 'CadastrosFavoritasController@favoritar')->name('favoritas.post');
    Route::delete('favoritas/{user}/{joia}', 'CadastrosFavoritasController@desfavoritar')->name('favoritas.delete');
    Route::get('palestra/zoom/{user}/{palestra}', 'AgendaController@relatorio')->name('relatorio.zoom');
    Route::get('compartilhar/whatsapp/{user}/{joia}', 'CadastrosFavoritasController@relatorioWhatsapp')->name('relatorio.whatsapp.compartilhar');
    Route::get('compartilhar/facebook/{user}/{joia}', 'CadastrosFavoritasController@relatorioFacebook')->name('relatorio.facebook.compartilhar');
    Route::get('compartilhar/email/{user}/{joia}', 'CadastrosFavoritasController@relatorioEmail')->name('relatorio.email.compartilhar');

    // Idiomas
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if (in_array($idioma, ['pt', 'en', 'es'])) {
            Session::put('locale', $idioma);
        }
        return redirect()->back();
    })->name('lang');

    // Login Evento
    Route::group([
        'prefix' => 'evento',
        'namespace' => 'Evento',
    ], function () {
        Route::post('login', 'Auth\AuthController@login')->name('evento.login.post');
        Route::post('cadastro', 'Auth\AuthController@create')->name('evento.register.post');
        Route::post('atualizar/{user}', 'Auth\AuthController@update')->name('evento.atualizar.user');
        Route::post('esqueci-minha-senha', 'Auth\PasswordController@sendResetLinkEmail')->name('evento.password-request.post');
        Route::get('redefinicao-de-senha/{token}', 'Auth\PasswordController@showResetForm')->name('evento.password-reset');
        Route::post('redefinicao-de-senha', 'Auth\PasswordController@reset')->name('evento.password-reset.post');
        Route::get('logout', 'Auth\AuthController@logout')->name('evento.logout');
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::resource('grupos-escolas', 'GruposEscolasController');
        Route::resource('joalheiros', 'JoalheirosController');
        Route::resource('joalheiros.joias', 'JoalheirosJoiasController');
        Route::resource('joalheiros.processo', 'JoalheirosProcessoController');
        Route::resource('joalheiros.serie', 'JoalheirosSerieController');
        Route::resource('banners-evento', 'BannersEventoController');
        Route::resource('banners-joalheiros', 'BannersJoalheirosController');
        Route::resource('banners-revista', 'BannersRevistaController');
        Route::resource('evento', 'EventoController', ['only' => ['index', 'update']]);
        Route::resource('tipos', 'TiposController');
        Route::resource('agenda', 'AgendaController', ['except' => 'show']);
        Route::resource('agenda.palestras', 'AgendaPalestrasController');
        Route::resource('videos', 'VideosController');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');

        Route::get('cadastros', 'CadastrosController@index')->name('painel.cadastros.index');
        Route::resource('assinaturas-livro', 'AssinaturasLivroController', ['only' => ['index', 'destroy']]);
        Route::get('relatorios/download-ebook', 'RelatoriosController@downloadEbook')->name('painel.relatorios.download-ebook');
        Route::get('relatorios/palestra-zoom', 'RelatoriosController@palestraZoom')->name('painel.relatorios.palestra-zoom');
        Route::get('relatorios/compartilhar-joia', 'RelatoriosController@compartilharJoia')->name('painel.relatorios.compartilhar-joia');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/AgendaController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\AgendaRequest;
use App\Models\Agenda;

class AgendaController extends Controller
{
    public function index()
    {
        $registros = Agenda::orderBy('data', 'ASC')->get();

        return view('painel.agenda.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.agenda.create');
    }

    public function store(AgendaRequest $request)
    {
        try {
            $input = $request->all();

            Agenda::create($input);

            return redirect()->route('painel.agenda.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Agenda $registro)
    {
        return view('painel.agenda.edit', compact('registro'));
    }

    public function update(AgendaRequest $request, Agenda $registro)
    {
        try {
            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.agenda.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Agenda $registro)
    {
        try {
            $registro->delete();

            return redirect()->route('painel.agenda.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/AgendaPalestrasController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\AgendaPalestrasRequest;
use App\Models\Agenda;
use App\Models\AgendaPalestra;

class AgendaPalestrasController extends Controller
{
    public function index(Agenda $agenda)
    {
        $palestras = AgendaPalestra::agenda($agenda->id)->ordenados()->get();

        return view('painel.agenda.palestras.index', compact('palestras', 'agenda'));
    }

    public function create(Agenda $agenda)
    {
        return view('painel.agenda.palestras.create', compact('agenda'));
    }

    public function store(AgendaPalestrasRequest $request, Agenda $agenda)
    {
        try {
            $input = $request->all();
            $input['agenda_id'] = $agenda->id;

            if (isset($input['imagem'])) $input['imagem'] = AgendaPalestra::uploadImagem();

            AgendaPalestra::create($input);

            return redirect()->route('painel.agenda.palestras.index', $agenda->id)->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Agenda $agenda, AgendaPalestra $palestra)
    {
        return view('painel.agenda.palestras.edit', compact('agenda', 'palestra'));
    }

    public function update(AgendaPalestrasRequest $request, Agenda $agenda, AgendaPalestra $palestra)
    {
        try {
            $input = $request->all();
            $input['agenda_id'] = $agenda->id;

            if (isset($input['imagem'])) $input['imagem'] = AgendaPalestra::uploadImagem();

            $palestra->update($input);

            return redirect()->route('painel.agenda.palestras.index', $agenda->id)->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Agenda $agenda, AgendaPalestra $palestra)
    {
        try {
            $palestra->delete();

            return redirect()->route('painel.agenda.palestras.index', $agenda->id)->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/AssinaturasLivroController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\Assinatura;

class AssinaturasLivroController extends Controller
{
    public function index()
    {
        $assinaturas = Assinatura::join('cadastros', 'cadastros.id', '=', 'assinaturas.cadastro_id')
            ->select('assinaturas.created_at as created_at', 'assinaturas.id as id', 'cadastros.nome as nome', 'cadastros.pais as pais', 'assinaturas.mensagem as mensagem')
            ->orderBy('assinaturas.created_at', 'DESC')->get();

        return view('painel.assinaturas.index', compact('assinaturas'));
    }

    public function destroy($id)
    {
        try {
            $assinatura = Assinatura::find($id);
            $assinatura->delete();

            return redirect()->route('painel.assinaturas-livro.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/BannersEventoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\BannersEventoRequest;
use App\Models\BannerEvento;

class BannersEventoController extends Controller
{
    public function index()
    {
        $registros = BannerEvento::ordenados()->get();
        $cores = ['#000000' => 'Preto', '#FFF' => 'Branco'];

        return view('painel.banners-evento.index', compact('registros', 'cores'));
    }

    public function create()
    {
        $cores = ['#000000' => 'Preto', '#FFF' => 'Branco'];

        return view('painel.banners-evento.create', compact('cores'));
    }

    public function store(BannersEventoRequest $request)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = BannerEvento::upload_imagem();

            BannerEvento::create($input);

            return redirect()->route('painel.banners-evento.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(BannerEvento $registro)
    {
        $cores = ['#000000' => 'Preto', '#FFF' => 'Branco'];

        return view('painel.banners-evento.edit', compact('registro', 'cores'));
    }

    public function update(BannersEventoRequest $request, BannerEvento $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = BannerEvento::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners-evento.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(BannerEvento $registro)
    {
        try {
            $registro->delete();

            return redirect()->route('painel.banners-evento.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/BannersJoalheirosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\BannersJoalheirosRequest;
use App\Models\BannerJoalheiros;

class BannersJoalheirosController extends Controller
{
    public function index()
    {
        $registros = BannerJoalheiros::ordenados()->get();
        $cores = ['#000000' => 'Preto', '#FFF' => 'Branco'];

        return view('painel.banners-joalheiros.index', compact('registros', 'cores'));
    }

    public function create()
    {
        $cores = ['#000000' => 'Preto', '#FFF' => 'Branco'];

        return view('painel.banners-joalheiros.create', compact('cores'));
    }

    public function store(BannersJoalheirosRequest $request)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = BannerJoalheiros::upload_imagem();

            BannerJoalheiros::create($input);

            return redirect()->route('painel.banners-joalheiros.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(BannerJoalheiros $registro)
    {
        $cores = ['#000000' => 'Preto', '#FFF' => 'Branco'];

        return view('painel.banners-joalheiros.edit', compact('registro', 'cores'));
    }

    public function update(BannersJoalheirosRequest $request, BannerJoalheiros $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = BannerJoalheiros::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners-joalheiros.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(BannerJoalheiros $registro)
    {
        try {
            $registro->delete();

            return redirect()->route('painel.banners-joalheiros.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CadastrosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\Cadastro;

class CadastrosController extends Controller
{
    public function index()
    {
        $cadastros = Cadastro::orderBy('created_at', 'DESC')->get();

        return view('painel.cadastros.index', compact('cadastros'));
    }
}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ConfiguracoesRequest;
use App\Models\Configuracao;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracao::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracao $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracao::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(Tools::routeIs(['painel.usuarios*', 'painel.configuracoes*', 'painel.politica*'])) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li @if(Tools::routeIs('painel.politica*')) class="active" @endif>
                            <a href="{{ route('painel.politica-de-privacidade.index') }}">Política de Privacidade</a>
                        </li>
                        <li @if(Tools::routeIs('painel.configuracoes*')) class="active" @endif>
                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                        </li>
                        <li @if(Tools::routeIs('painel.usuarios*')) class="active" @endif>
                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                        </li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">

    <li class="dropdown @if(Tools::routeIs('painel.banners*')) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Home <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.banners-evento*')) class="active" @endif>
                <a href="{{ route('painel.banners-evento.index') }}">Banners Evento</a>
            </li>
            <li @if(Tools::routeIs('painel.banners-joalheiros*')) class="active" @endif>
                <a href="{{ route('painel.banners-joalheiros.index') }}">Banners Joalheiros</a>
            </li>
            <li @if(Tools::routeIs('painel.banners-revista*')) class="active" @endif>
                <a href="{{ route('painel.banners-revista.index') }}">Banners Revista</a>
            </li>
        </ul>
    </li>

    <li @if(Tools::routeIs('painel.evento*')) class="active" @endif>
        <a href="{{ route('painel.evento.index') }}">Evento</a>
    </li>

    <li class="dropdown @if(Tools::routeIs('painel.tipos*')) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Encontros e Mais <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.agenda*')) class="active" @endif>
                <a href="{{ route('painel.agenda.index') }}">Agenda</a>
            </li>
            <li @if(Tools::routeIs('painel.videos*')) class="active" @endif>
                <a href="{{ route('painel.videos.index') }}">Vídeos</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs('painel.tipos*')) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Joias & Joalheiros <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.joalheiros*')) class="active" @endif>
                <a href="{{ route('painel.joalheiros.index') }}">Joalheiros</a>
            </li>
            <li @if(Tools::routeIs('painel.tipos*')) class="active" @endif>
                <a href="{{ route('painel.tipos.index') }}">Tipos de Joias</a>
            </li>
        </ul>
    </li>

    <li @if(Tools::routeIs('painel.grupos-escolas*')) class="active" @endif>
        <a href="{{ route('painel.grupos-escolas.index') }}">Grupos & Escolas</a>
    </li>

    <li @if(Tools::routeIs('painel.assinaturas-livro*')) class="active" @endif>
        <a href="{{ route('painel.assinaturas-livro.index') }}">Assinaturas</a>
    </li>

    <li @if(Tools::routeIs('painel.cadastros*')) class="active" @endif>
        <a href="{{ route('painel.cadastros.index') }}">Cadastros</a>
    </li>

    <li class="dropdown @if(Tools::routeIs('painel.relatorios*')) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Relatórios <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.relatorios.download-ebook')) class="active" @endif>
                <a href="{{ route('painel.relatorios.download-ebook') }}">Download E-book</a>
            </li>
            <li @if(Tools::routeIs('painel.relatorios.palestra-zoom')) class="active" @endif>
                <a href="{{ route('painel.relatorios.palestra-zoom') }}">Palestra Zoom</a>
            </li>
            <li @if(Tools::routeIs('painel.relatorios.compartilhar-joia')) class="active" @endif>
                <a href="{{ route('painel.relatorios.compartilhar-joia') }}">Compartilhar Joia</a>
            </li>
        </ul>
    </li>

</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('app.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/vendor.painel.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel.css') }}">
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/vendor/jquery-mask-plugin-master/dist/jquery.mask.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/jquery-maskmoney-master/dist/jquery.maskMoney.min.js') }}"></script>
    <script src="{{ asset('assets/js/vendor.painel.js') }}"></script>
    <script src="{{ asset('assets/js/painel.js') }}"></script>
</body>
</html>